### ISSUE TITLE
VestaCP dns won't propagate

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#100]
Hi, i install the image in aws. I can´t use the dns system of vestacp because the dns dont propagate, i already open all the ports that we require.

![2](https://user-images.githubusercontent.com/46969064/65909378-e3efeb00-e39e-11e9-96db-ba0e798fea4c.png)
![Anotación 2019-09-30 162404](https://user-images.githubusercontent.com/46969064/65909380-e3efeb00-e39e-11e9-9693-88cb0d3292fe.png)

**Comment by noogen** [comment]
Hi, I don't really use DNS for this because I either use ROUTE53 or whoever I'm hosting at (Linode, Vultr, Digital Ocean, etc..).  Though, I can definitely help to troubleshoot.  

Step 1 > Let see if you can connect
  Did you add the port to your docker-compose?  https://github.com/niiknow/vestacp/blob/master/docker-compose.yml#L13
  Is it running by checking if you can telnet into the port 53?  If not, is bind9 service running?  DNS is disabled by default so you have to add `./bind9 start` to startup like so https://github.com/niiknow/vestacp/blob/master/rootfs/sysprepz/admin/bin/my-startup.sh#L22

Step 2 > https://blog.hostripples.com/how-to-set-up-own-name-servers-in-vesta-control-panel/
Check vesta forum for name server setup here: https://forum.vestacp.com/viewforum.php?f=13
Example: https://forum.vestacp.com/viewtopic.php?t=11496

**Comment by patsotoe** [comment]
Hi friend, first thanks for you support in awesome docker image. i already check your suggestions befor to start this topic, but i check again and all the setting are right, but this doesn´t work altought-

1)  I already add the ./bind9 startup.
2) I already checked this post with not luck, all the setting are setting rigthly, i just reboot the machine.
