### ISSUE TITLE
activate roundcube

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#101]
Hi friend, it´s me again. I active roundcube with not luck using your tip, any idea how i can resolve this problem?

your command:
rsync -a /opt/vestacp/vesta/etc/apache2/conf-d/roundcube.conf /opt/vestacp/vesta/etc/apache2/conf.d

i use the following command with not luck:

rsync -a /opt/vestacp/vesta/etc/apache2/conf-d/roundcube.conf /opt/vestacp/vesta/etc/apache2/conf.d

Thanks for your help again.

**Comment by noogen** [comment]
1.  Check that your both apache and nginx template are "default" - this is to make sure that nginx is proxying everything (outside of /dbadmin path) to apache.
2.  Make sure you add to startup: `/exim4 start` and `/dovecot start`.  Add any necessary port to docker: 25, 110, 143, 465, 993, 995  
3.  Do the above rsync you mentioned and don't forget to restart apache2

**Comment by patsotoe** [comment]
hi friend finally i reinstall all again and enabled roundube solutions my problema. Thanks for your help, how i can change the port 25 for listening emails, because is blocked by amazon.

**Comment by noogen** [comment]
In docker, you can map any external port -> 25 so it's really up to you.  Though, sending email out to port 25 would be a problem as Amazon probably blocking that too.  I would suggest you use some other vendor that doesn't block email like Digital Ocean, Linode, Vultr, etc...  Otherwise, you will have to submit a request and be prepare to defend yourself with Amazon.  They will most likely suggest you use the services like SES and stuff...

**Comment by patsotoe** [comment]
thanks, i decide to move to digital ocean the server of emails.
