### ISSUE TITLE
error dbadmin

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#102]
hi, i have a problem to access to the url dbadmin . The service is working but i can´t access. Im running the last image of vestacp.

**Comment by patsotoe** [comment]
i check this for my main domain and its working great! but whit my others domain give a error like not found the page.

**Comment by noogen** [comment]
@patsotoe This was done on purpose for security.  You've ran website and you can probably agree that one of the biggest scan on the internet for website is phpmyadmin or any kind of dbadmin.  This will also slow down your server.  To enable it, simply put a "conf" file in your private directory.

```
echo "include /etc/nginx/conf.d/dbadmin.inc;" > /home/{user}/web/{website}/private/dbadmin.conf
nginx -t
nginx -s reload
```

This is because my nginx config will read anything with extension "conf" in the private folder.

**Comment by patsotoe** [comment]
thanks por the explanation.
