### ISSUE TITLE
Not an issue, but question to maintainer

### ISSUE THREAD

**Issue by dusansusic** [niiknow/vestacp#19]
Hi, great work. I have question regarding VestaCP running in container. What is the purpose of this? You are actually maintaining Ubuntu which is in container, not a real host where container is running? So what's the purpose? Also, maybe I am wrong but the point is to have one process in container, not quite big number included there :) What do you think?

**Comment by noogen** [comment]
@dusansusic agree.  I actually responded to the same question here when I initially created this container: https://forum.vestacp.com/viewtopic.php?f=18&t=12953

> Since it's a monolithic image, it does defeat the purpose of docker/microservice design. Of course, it was for a different purpose. I just want to host with VESTA but didn't want to blow away or mess up my external VPS setup.

I also wanted something I can control, experiment, and also help me learn more about the inner working of Vesta.  This give me full confident of doing whatever I want and being able to completely reset it to any state that I want.

I also run this in Production and have script on VestaCP cron to backup to AWS s3.  I have full confident of being able to quickly restore my VestaCP to any VPS providers (DigitalOcean, Linode, Vultr, etc..) in a disaster recovery situation.

**Comment by noogen** [comment]
Also, Vesta is currently moving very slow, see all the issues here (https://github.com/serghey-rodin/vesta/issues).  With the container, I was able to experiment with new features such as: Panel and email SSL, multiple php fcgi and fpm, nginx pagespeed, custom nginx templates, and so on.

This panel has provide me with better understanding of Vesta.  I also use it to validate bugs and experiment with new features.  I apply my experience to help out on various Vesta repo issues here (https://github.com/serghey-rodin/vesta/pull/1355) and is slowly working on getting these features into Vesta.  It's been slow because Vesta is currently moving very slowly.

**Comment by noogen** [comment]
Closing inactive issue.
