### ISSUE TITLE
Not able to get VestaCP working

### ISSUE THREAD

**Issue by kalyway** [niiknow/vestacp#24]
So I'm having issues getting the VestaCP docker working. I install it through portainer and make all the ports public so I can try to access VestaCP from my client, however, none of the ports work except for one. The one that works also only gives 4571c112d7a1.example.com "Powered by Nginx".

**Comment by OutdoorTree90990** [comment]
Yup, get the same thing. Thought I was going crazy

**Comment by noogen** [comment]
I just came back from long Vacation and start to work on upgrading the container to 0.9.8-18.  Everything seem to work so far.  I test it locally and it runs fine.  I run inside rancher environment and that works too.

@kalyway I'm not familiar with portainer.  It said Nginx because because I modified default content from Vesta to Nginx: https://github.com/niiknow/vestacp/blob/7da290ba8edcf7025ce2a3e9929baef2d5141702/Dockerfile#L293

@Admin9705 are you using portainer too?

Can you provide more details of the issue?  Also, please try the latest docker build/image.  Thanks.

**Comment by noogen** [comment]
Closing due to no response.
