### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by markolofsen** [niiknow/vestacp#46]
By default I can't to open my web site through HTTPS.
Also I don't see no one https config in /home/admin/web/...
What I have to do?

**Comment by noogen** [comment]
If no $VESTA_DOMAIN variable was provided, there should be a default website under '/home/admin/web/6da8868c6763.example.com' folder.  This is only http website on port 80 and no https on port 443.

The default VESTA control panel website is under '/usr/local/vesta/web' folder using ssl under the '/usr/local/vesta/ssl' folder which is mapped to port 8083 (with auto-signed ssl).

Can you provide any log from docker otherwise it's hard for me to troubleshoot?

**Comment by markolofsen** [comment]
Ok, but I didn't specified $VESTA_DOMAIN when did first docker-install. What can I do?
Can I fixed it somewhere else?

**Comment by noogen** [comment]
You don't need $VESTA_DOMAIN for ssl to work on port 443.  It's just not going to be a trusted cert.  I'm not sure how I can help you here without any error log or example site.

**Comment by Kupinet** [comment]
@noogen I'll ask differently) Where it is necessary to specify $VESTA_DOMAIN? With first install from the docker or somewhere else in the VestaCP files?

**Comment by noogen** [comment]
@Kupinet answer for the How:  It's not necessary to have it on install from docker.  You can pass it anytime you need the panel to have SSL.  It is part of the startup process -  https://github.com/niiknow/vestacp/blob/master/rootfs/etc/my_init.d/startup.sh#L53 - so you can pass it when you are ready.  Just make sure the domain DNS is configured to your server IPv4 address.  It work best on a system with a single IPv4.

As for the where answer: https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers
