### ISSUE TITLE
AWStats Error

### ISSUE THREAD

**Issue by LenKiMo** [niiknow/vestacp#7]
After enable AWStats for a website, I got this error:
```
Error: LogFile parameter is not defined in config/domain file 

Setup ('/etc/awstats/conf' file, web server or permissions) may be wrong.
Check config file, permissions and AWStats documentation (in 'docs' directory).
```

There is a little question that `/etc/awstats` folder only include these file:
```
awstats.conf  awstats.conf.local  awstats.abc.com.conf
```

Do you have any advise about this?

**Comment by noogen** [comment]
I have not redirect "/etc/awstat" folder so it probably won't survive reboot.   AWStat folder config is in /usr/lib/cgi-bin/awstats.pl and its' confs are symbolically link from /etc/awstats to /home/user/conf/awstats.domain.conf.  I will fix this in the future release.

My guess is that one of your domain previously has setup with awstats and now there is not a link of the file to /etc/awstats because of a reboot?  Find out which one and add the symbolic link manually or use the Vesta Panel.  To find out which site/user has previously setup with awstats:

```
sudo find -O4 -L /home -name "awstats.*.conf"
```

Additional troubleshooting.  By understanding how it work, maybe this will help you troubleshoot:

1. In Vesta Panel, look at user "admin"  cron run: sudo /usr/local/vesta/bin/v-update-sys-queue webstats 
2. Which call: v-update-web-domain-stat
3. Which call: /usr/lib/cgi-bin/awstats.pl

edit /usr/lib/cgi-bin/awstats.pl and update this line to add debug:
```
opts="-config=$domain_idn -staticlinks -update -output"
```

to
```
opts="-config=$domain_idn -staticlinks -update -output -debug=2"
```

This allow it to display more message with error.  No worry, it's only debugging and a reboot will revert your change back.

**Comment by LenKiMo** [comment]
I reinstall the docker with 0.8.48, the AWStats seems like still with same error.
It still need to I do it myself?

**Comment by noogen** [comment]
After reinstall 0.8.48, remove and re-add awstats on all domains that use awstats.  This will re-create the symbolic link and persist the result across reboot.

If you upgrade to 0.8.48 from another version, do this to create awstats:
```
mkdir -p /vesta/etc/awstats
rsync -a /vesta-start/etc/awstats /vesta/etc/awstats
rm -f /etc/awstats 
ln -s /vesta/etc/awstats /etc/awstats 
```

**Comment by LenKiMo** [comment]
By disable AWStats in VestaCP and re-enable it the problem fixed.
Thanks for your work.
