### ISSUE TITLE
Delete default domain

### ISSUE THREAD

**Issue by limogin** [niiknow/vestacp#73]
I see this error when I try to delete the default domain. Is it possible? 

`"Error: Parsing error" `

In vesta logs I see 

`/var/log/vesta/error.log`

```
2018-12-28 13:54:58 v-delete-web-domain  'admin' 'mydomain-.com' 'no' [Error 12]
2018-12-28 13:54:58 v-delete-domain  'admin' 'mydomain.com' [Error 12]
```

Thanks,

**Comment by noogen** [comment]
I'm not sure if Vesta allow you to delete default domain.  Vesta auto panel ssl use a website/default domain on the `admin` account to get the cert.  If you provide a `hostname`, this will add an additional website to the `admin` account for cert.  You can then delete the default domain, but it will still show up as having 2 domains in the `admin` account.  Just an error/quirk that I would ignore because you should not be using admin account for hosting.  Create a different user to host so you can fully utilize the backup and restore of a user to vestacp on different server.

I'm not sure I can resolve this.  If you have a suggestion, let me know.
