### ISSUE TITLE
phpMyAdmin: Connection for controluser as defined in your configuration failed.

### ISSUE THREAD

**Issue by pschuurmans** [niiknow/vestacp#85]
While logging into phpMyAdmin with the credentials of the auto generated db table, I'm getting the following error on the Import tab.

```
Warning in ./libraries/plugin_interface.lib.php#532
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_import.lib.php#368: PMA_pluginGetOptions(
string 'Import',
array,
)
./libraries/display_import.lib.php#453: PMA_getHtmlForImportOptionsFormat(array)
./libraries/display_import.lib.php#684: PMA_getHtmlForImport(
string '5ce295a3eb257',
string 'database',
string 'admin_default',
string '',
integer 629145600,
array,
NULL,
NULL,
string '',
)
./db_import.php#40: PMA_getImportDisplay(
string 'database',
string 'admin_default',
string '',
integer 629145600,
)
```

**Comment by noogen** [comment]
Looks like phpMyAdmin that get installed by `Vesta` is old and does not work with php7.2 https://medium.com/@chaloemphonthipkasorn/%E0%B9%81%E0%B8%81%E0%B9%89-bug-phpmyadmin-php7-2-ubuntu-16-04-92b287090b01

Here's a bug report from `Vesta` https://github.com/serghey-rodin/vesta/issues/1684

This is where disabling by default is a good thing.   Since this is `ubuntu`, I'm going to try to fix it by adding the `universe` ppa to get the latest phpmyadmin - https://launchpad.net/ubuntu/+source/phpmyadmin

**Comment by noogen** [comment]
Also discover that latest phppgadmin has issue so I decided to swap out phpMyAdmin and phpPgAdmin for `adminer` in 1.8.0 build.  In addition, the config allow user to customize with basic auth or something to protect against attack - https://github.com/niiknow/vestacp/blob/master/rootfs/etc/nginx/conf.d/dbadmin.inc#L11

**Comment by pschuurmans** [comment]
Nice move. The phpMyAdmin and phpPgAdmin buttons are still visisble on the database page. Possible to swap it with a Adminer button?

**Comment by noogen** [comment]
Close as resolved with adminer.
