### ISSUE TITLE
Automatically backup to /backup

### ISSUE THREAD

**Issue by schulluk** [niiknow/vestacp#9]
Hi,
I tried your awesome work and wondered if I need to active the incrond somehow?
Currently, the /backup folder does not contain anything.
How often are the data synced to /backup?

**Comment by noogen** [comment]
Your login/creds are supposed to backup (rsync) to the /backup/.etc (hidden) folder.  Have you check the folder?  ls -la /backup/.etc

It has been working fine for me for docker 1.2-1.3.x on existing co-locate production environment, but I recently found that it doesn't work on my new servers.  My new setup is on Linode with latest docker ce 17.06 and it doesn't seem to sync on changes.

I've added cron.hourly to guarantee the sync.   Use latest image 0.8.57 and up.   Reason:  I've known for while that INotify api (use by incrond) is not consistent across different implementation inside containers:  https://github.com/moby/moby/issues/18246

This is why the cron.hourly was setup as backup in case inotify fail.  https://github.com/niiknow/vestacp/commit/dea4aa7b9aa949c86f5b5b1efd8898b7e4fe6e09

You can also manually run: /usr/bin/backup-creds.sh

**Comment by noogen** [comment]
Oh, and if you're looking for Vesta User's backup, you need to go into VestaCP and trigger the backup for a specific user (admin) at least one time.  Sometime, this help Vesta to start the cron job for backing up all your users.  It's not necessary and should work, but I usually do this to make sure instead of waiting for the daily backup to happen.  That way, I can verify that it has successfully backup by checking the existence of some file like /backup/admin.2017-07-24.tar - wait for at least 10 minutes before checking.

Additional troubleshooting:

1.  Is cron running?  Check to make sure that /etc/service/cron/down and /etc/service/syslog-ng/down does not exists.
```
tail /var/log/cron.log
```

2. Is VestaCP backup running? check /usr/local/vesta/log
```
tail /usr/local/vesta/log/error.log
tail /usr/local/vesta/log/backup.log
tail /usr/local/vesta/log/system.log
```
check syslog to make sure vesta cron is running: tail /var/log/syslog

It should have some message like below that run every 5 minutes:
```
Jul 24 19:45:01 c83d5af39ba7 CRON[15688]: (admin) CMD (sudo /usr/local/vesta/bin/v-update-sys-queue backup)
```

**Comment by schulluk** [comment]
Thanks for your fast feedback.
I just figured out that I didn't have the latest version, because it was just 3 hours old on github when I tried your vestacp.
Currently, my /backup contains only 2 daily tar archives, but I will check it tomorrow again. Will let you know if it works :-)

VestaCP backup is running every 5 minutes 👍

**Comment by schulluk** [comment]
When I check the cron folders I get:

```
ls -lha /etc/cron.*
/etc/cron.d:
total 16K
drwxr-xr-x  2 root root 4.0K Jul  2 09:12 ./
drwxr-xr-x 80 root root 4.0K Jul 26 10:17 ../
-rw-r--r--  1 root root   47 Jul  2 09:12 kernel
-rw-r--r--  1 root root  102 May  3  2015 .placeholder

/etc/cron.daily:
total 40K
drwxr-xr-x  2 root root 4.0K Jul  2 12:46 ./
drwxr-xr-x 80 root root 4.0K Jul 26 10:17 ../
-rwxr-xr-x  1 root root 1.5K Apr  1 21:39 apt-compat*
-rwxr-xr-x  1 root root  314 Apr 19 00:11 aptitude*
-rwxr-xr-x  1 root root  355 Oct 25  2016 bsdmainutils*
-rwxr-xr-x  1 root root 1.6K Feb 22 22:50 dpkg*
-rwxr-xr-x  1 root root   89 May  6  2015 logrotate*
-rwxr-xr-x  1 root root 1.1K Dec 13  2016 man-db*
-rwxr-xr-x  1 root root  249 Feb 24 01:33 passwd*
-rw-r--r--  1 root root  102 May  3  2015 .placeholder

/etc/cron.hourly:
total 12K
drwxr-xr-x  2 root root 4.0K May 29 16:33 ./
drwxr-xr-x 80 root root 4.0K Jul 26 10:17 ../
-rw-r--r--  1 root root  102 May  3  2015 .placeholder

/etc/cron.monthly:
total 12K
drwxr-xr-x  2 root root 4.0K May 29 16:33 ./
drwxr-xr-x 80 root root 4.0K Jul 26 10:17 ../
-rw-r--r--  1 root root  102 May  3  2015 .placeholder

/etc/cron.weekly:
total 16K
drwxr-xr-x  2 root root 4.0K May 29 16:37 ./
drwxr-xr-x 80 root root 4.0K Jul 26 10:17 ../
-rwxr-xr-x  1 root root  723 Dec 13  2016 man-db*
-rw-r--r--  1 root root  102 May  3  2015 .placeholder
```


Running `$ crontab -l` returns no crontab for the user.

Executing `$ ls -lha /etc/incron.d/`returns only one file: .placeholder

Is this correct? Where can I find the cronjob to backup to /backup/.etc ?

**Comment by noogen** [comment]
incron is run as root, the file is here: /var/spool/incron/root
If you did not see any files inside of in /backup/.etc folder, please run: /usr/bin/backup-creds.sh

Check to make sure that incrond is running:
```
root@c83d5af39ba7:~# ps -uax | grep incron
root        26  0.0  0.0  21824   284 ?        Ss   Jul24   0:00 /usr/sbin/incrond -f /etc/incron.conf
root      3860  0.0  0.0  14232   940 pts/0    R+   12:36   0:00 grep --color=auto incron
```

This is how I currently start/run incrond: https://github.com/niiknow/vestacp/blob/master/files/etc/my_init.d/startup.sh#L32

I need to move incrond to runit service instead of systemv as it is unreliable in docker.   I'll also move incron.d from root into /etc/incron.d for better visibility.

**Comment by schulluk** [comment]
With the latest version, it does correctly backup data to /backup/.etc
I did a docker-compose down && docker-compose up -d and it kept my password for the admin account!
Thank you!

**Comment by axifhussain** [comment]
sir plz guid me my vestacp backup cron my disk is full with daily backup file how to i set that when new backup generate old automatically delete. i delete my old backup files from putty every 3 days but i want the old backup automatically delete.
